SELECT A.NAME AS CATEGORY_NAME,
	SUM(F.AMOUNT) AS RENTAL_REVENUE
FROM CATEGORY A
JOIN FILM_CATEGORY B ON A.CATEGORY_ID = B.CATEGORY_ID
JOIN FILM C ON B.FILM_ID = C.FILM_ID
JOIN INVENTORY D ON C.FILM_ID = D.FILM_ID
JOIN RENTAL E ON D.INVENTORY_ID = E.INVENTORY_ID
JOIN PAYMENT F ON E.RENTAL_ID = F.RENTAL_ID
GROUP BY A.CATEGORY_ID,
	A.NAME
ORDER BY RENTAL_REVENUE DESC;
