SELECT FILM.TITLE FILMTITLE,
	CATEGORY.NAME CATEGORY,
	SUM(PAYMENT.AMOUNT) AS TOTAL_AMOUNT,
	SUM(RENTAL.RETURN_DATE - RENTAL.RENTAL_DATE) AS TIME_RENTED
FROM PAYMENT
JOIN RENTAL ON (PAYMENT.RENTAL_ID = RENTAL.RENTAL_ID)
JOIN INVENTORY ON (RENTAL.INVENTORY_ID = INVENTORY.INVENTORY_ID)
JOIN FILM ON (INVENTORY.FILM_ID = FILM.FILM_ID)
JOIN FILM_CATEGORY ON (FILM_CATEGORY.FILM_ID = FILM.FILM_ID)
JOIN CATEGORY ON (FILM_CATEGORY.CATEGORY_ID = CATEGORY.CATEGORY_ID)
WHERE CATEGORY.NAME IN ('Sports')
GROUP BY FILM.TITLE,
	CATEGORY.NAME
ORDER BY TOTAL_AMOUNT DESC
