SELECT LANGUAGE.NAME Language,
	FILM.TITLE FILM_TITLE,
	COUNT(INVENTORY.FILM_ID) AS FREQUENCY,
	SUM(PAYMENT.AMOUNT) REVENUE
FROM LANGUAGE
INNER JOIN FILM ON FILM.LANGUAGE_ID = LANGUAGE.LANGUAGE_ID
INNER JOIN INVENTORY ON INVENTORY.FILM_ID = FILM.FILM_ID
INNER JOIN RENTAL ON RENTAL.INVENTORY_ID = INVENTORY.INVENTORY_ID
FULL JOIN PAYMENT ON PAYMENT.RENTAL_ID = RENTAL.RENTAL_ID
GROUP BY FILM.TITLE,
	LANGUAGE.NAME
ORDER BY FREQUENCY DESC;
