
SELECT C.COUNTRY,
	MAX(CS.FIRST_NAME) AS CUSTOMER,
	MAX(CS.EMAIL) AS EMAIL,
	MAX(AD.ADDRESS) ADDRESS,
	MAX(AD.DISTRICT) DISTRICT,
	MAX(CI.CITY) CITY,
	SUM(P.AMOUNT) AS REVENUE
FROM COUNTRY C
JOIN CITY CI USING (COUNTRY_ID)
JOIN ADDRESS AD ON CI.CITY_ID = AD.CITY_ID
JOIN CUSTOMER CS ON CS.ADDRESS_ID = AD.ADDRESS_ID
JOIN PAYMENT P ON CS.CUSTOMER_ID = P.CUSTOMER_ID
GROUP BY COUNTRY
ORDER BY REVENUE DESC
