WITH ACTOR_CNT AS
	(SELECT FILM_ID,
			COUNT(ACTOR_ID) NUMBER_OF_ACTORS
		FROM FILM_ACTOR
		GROUP BY FILM_ID)
SELECT COUNT(ACTOR_CNT.FILM_ID) FREQUENCY,
	ACTOR_CNT.NUMBER_OF_ACTORS FREQUENCY
FROM ACTOR_CNT
GROUP BY ACTOR_CNT.NUMBER_OF_ACTORS
ORDER BY ACTOR_CNT.NUMBER_OF_ACTORS
