WITH RENTAL_STATUS AS
	(SELECT STORE.STORE_ID,
			ADDRESS,
			RENTAL_ID,
			RETURN_DATE,
			RENTAL_DATE,
			F.RENTAL_DURATION,
			CASE
							WHEN RENTAL_DURATION > CAST(RETURN_DATE AS DATE) - CAST(RENTAL_DATE AS DATE) THEN 'Returned early'
							WHEN RENTAL_DURATION = CAST(RETURN_DATE AS DATE) - CAST(RENTAL_DATE AS DATE) THEN 'Returned on time'
							ELSE 'Returned late'
			END AS RETURN_STATUS
		FROM RENTAL
		JOIN INVENTORY INV USING (INVENTORY_ID)
		JOIN FILM F ON INV.FILM_ID = F.FILM_ID
		JOIN STORE ON INV.STORE_ID = STORE.STORE_ID
		JOIN ADDRESS ON ADDRESS.ADDRESS_ID = STORE.ADDRESS_ID)
SELECT STORE_ID,
	ADDRESS,
	RETURN_STATUS,
	COUNT(*) AS "films count"
FROM RENTAL_STATUS
GROUP BY RETURN_STATUS,
	STORE_ID,
	ADDRESS
ORDER BY RETURN_STATUS;
