WITH C AS
	(SELECT STORE.STORE_ID,
			FILM_CATEGORY.CATEGORY_ID,
			CATEGORY.NAME GENRE,
			COUNT(INVENTORY.FILM_ID) AS FREQUENCY,
			SUM(PAYMENT.AMOUNT) REVENUE
		FROM STORE
		JOIN INVENTORY ON INVENTORY.STORE_ID = STORE.STORE_ID
		JOIN RENTAL ON RENTAL.INVENTORY_ID = INVENTORY.INVENTORY_ID
		JOIN PAYMENT ON PAYMENT.RENTAL_ID = RENTAL.RENTAL_ID
		JOIN FILM_CATEGORY ON FILM_CATEGORY.FILM_ID = INVENTORY.FILM_ID
		INNER JOIN CATEGORY ON FILM_CATEGORY.CATEGORY_ID = CATEGORY.CATEGORY_ID
		GROUP BY STORE.STORE_ID,
			FILM_CATEGORY.CATEGORY_ID,
			CATEGORY.NAME
		ORDER BY FREQUENCY DESC)
SELECT C.STORE_ID,
	C.NAME CATEGORY_NAME,
	MAX(C.FREQUENCY) FREQUENCY,
	SUM(C.REVENUE) TOTAL_REVENUE
FROM C
GROUP BY C.STORE_ID,
	C.CATEGORY_ID,
	C.NAME
ORDER BY MAX(C.FREQUENCY) DESC;
